create table fare (id bigint generated by default as identity, base_fare decimal(19,2), daily_cap decimal(19,2), from_zone bigint, to_zone bigint, week_ly_cap decimal(19,2), primary key (id))
create table journey (id bigint generated by default as identity, applicable_fare decimal(19,2), user_id bigint, fare bigint, surcharge bigint, primary key (id))
create table surcharge (id bigint generated by default as identity, date_from date, date_to date, day_from varchar(255), day_to varchar(255), surcharge decimal(19,2), surcharge_type varchar(255), time_from timestamp, time_to timestamp, fare bigint, primary key (id))
alter table journey add constraint FK7m99isd29ku8hyetaaftk65af foreign key (fare) references fare
alter table journey add constraint FK7u3im8x5i6cw45lfh9wyyiwt0 foreign key (surcharge) references surcharge
alter table surcharge add constraint FKrp8fed8yi139wtfn0f0oav1di foreign key (fare) references fare
